/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-04-19 21:34:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ptCadCliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<title>Livraria Astronauta</title>\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\">\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<h1>Cadastro</h1>\n");
      out.write("\t\t");
out.print("Preencha os campos abaixo.");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<form action=\"receberDados.jsp\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\tNome: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"nome\" name=\"nome\"><br>\n");
      out.write("\t\t\tCPF: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"cpf\" name=\"cpf\"><br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Endereco -->\n");
      out.write("\t\t\tRua: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"rua\" name=\"rua\"><br>\n");
      out.write("\t\t\tN°: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"numero\" name=\"numero\"><br>\n");
      out.write("\t\t\tBairro: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"bairro\" name=\"bairro\"><br>\n");
      out.write("\t\t\tCidade: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"cidade\" name=\"cidade\"><br>\n");
      out.write("\t\t\tCep: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"cep\" name=\"cep\"><br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Telefones -->\n");
      out.write("\t\t\tTelefone Fixo: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"telFixo\" name=\"telFixo\"><br>\t\n");
      out.write("\t\t\tCelular 1: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"celular1\" name=\"celular1\"><br>\n");
      out.write("\t\t\tCelular 2: <br>\n");
      out.write("\t\t\t<input type=\"text\" id=\"celular2\" name=\"celular2\"><br>\t\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Cadastrar\"><br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</form>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
